
spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/Documents/study/h2-repo/routine
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  profiles:
    active: local
  jackson:
    time-zone: Asia/Seoul
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /webjars/swagger-ui/**.*

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

